# config/application.yml
defaults: &defaults
  host_url: http://localhost:3000
  forum_url: http://forum.ogromno.ru
  billing:
    url: http://localhost:3001
    login: ogromno
    password: 123456789
  verification_code_valid_time: 24.hours

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults