# config/application.yml
defaults: &defaults
  host_url: http://localhost:3000
  billing:
    url: http://localhost:3001
    login: ogromno
    password: 123456789

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults