require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PackageListsController do

  # This should return the minimal set of attributes required to create a valid
  # PackageList. As you add validations to PackageList, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PackageListsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all package_lists as @package_lists" do
      package_list = PackageList.create! valid_attributes
      get :index, {}, valid_session
      assigns(:package_lists).should eq([package_list])
    end
  end

  describe "GET show" do
    it "assigns the requested package_list as @package_list" do
      package_list = PackageList.create! valid_attributes
      get :show, {:id => package_list.to_param}, valid_session
      assigns(:package_list).should eq(package_list)
    end
  end

  describe "GET new" do
    it "assigns a new package_list as @package_list" do
      get :new, {}, valid_session
      assigns(:package_list).should be_a_new(PackageList)
    end
  end

  describe "GET edit" do
    it "assigns the requested package_list as @package_list" do
      package_list = PackageList.create! valid_attributes
      get :edit, {:id => package_list.to_param}, valid_session
      assigns(:package_list).should eq(package_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PackageList" do
        expect {
          post :create, {:package_list => valid_attributes}, valid_session
        }.to change(PackageList, :count).by(1)
      end

      it "assigns a newly created package_list as @package_list" do
        post :create, {:package_list => valid_attributes}, valid_session
        assigns(:package_list).should be_a(PackageList)
        assigns(:package_list).should be_persisted
      end

      it "redirects to the created package_list" do
        post :create, {:package_list => valid_attributes}, valid_session
        response.should redirect_to(PackageList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved package_list as @package_list" do
        # Trigger the behavior that occurs when invalid params are submitted
        PackageList.any_instance.stub(:save).and_return(false)
        post :create, {:package_list => {  }}, valid_session
        assigns(:package_list).should be_a_new(PackageList)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PackageList.any_instance.stub(:save).and_return(false)
        post :create, {:package_list => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested package_list" do
        package_list = PackageList.create! valid_attributes
        # Assuming there are no other package_lists in the database, this
        # specifies that the PackageList created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PackageList.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => package_list.to_param, :package_list => { "these" => "params" }}, valid_session
      end

      it "assigns the requested package_list as @package_list" do
        package_list = PackageList.create! valid_attributes
        put :update, {:id => package_list.to_param, :package_list => valid_attributes}, valid_session
        assigns(:package_list).should eq(package_list)
      end

      it "redirects to the package_list" do
        package_list = PackageList.create! valid_attributes
        put :update, {:id => package_list.to_param, :package_list => valid_attributes}, valid_session
        response.should redirect_to(package_list)
      end
    end

    describe "with invalid params" do
      it "assigns the package_list as @package_list" do
        package_list = PackageList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PackageList.any_instance.stub(:save).and_return(false)
        put :update, {:id => package_list.to_param, :package_list => {  }}, valid_session
        assigns(:package_list).should eq(package_list)
      end

      it "re-renders the 'edit' template" do
        package_list = PackageList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PackageList.any_instance.stub(:save).and_return(false)
        put :update, {:id => package_list.to_param, :package_list => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested package_list" do
      package_list = PackageList.create! valid_attributes
      expect {
        delete :destroy, {:id => package_list.to_param}, valid_session
      }.to change(PackageList, :count).by(-1)
    end

    it "redirects to the package_lists list" do
      package_list = PackageList.create! valid_attributes
      delete :destroy, {:id => package_list.to_param}, valid_session
      response.should redirect_to(package_lists_url)
    end
  end

end
